services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile 
    ports:
      - "8080:8080" 
    depends_on:
      - users-api
      - tasks-api
    networks:
      - app_network

  users-api:
    build:
      context: .
      dockerfile: src/UserService.Api/Dockerfile
    ports:
      - "5221:5221"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5221
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=taskmanagerdb;Username=postgres;Password=postgres;SslMode=Disable;Trust Server Certificate=true
    depends_on:
      db:
        condition: service_healthy
      rabbitmq: 
        condition: service_healthy
    networks:
      - app_network

  tasks-api:
    build:
      context: .
      dockerfile: src/TaskService.Api/Dockerfile
    ports: []
      # - "8081:8081" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5115
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=taskmanagerdb;Username=postgres;Password=postgres;SslMode=Disable;Trust Server Certificate=true
    depends_on:
      db:
        condition: service_healthy
      rabbitmq: 
        condition: service_healthy
    networks:
      - app_network

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=taskmanagerdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d taskmanagerdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management 
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - users-api
      - tasks-api
      - api-gateway
    networks:
      - app_network

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000" 
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app_network

volumes:
  postgres_data:
  grafana_data:

networks:
  app_network:
    driver: bridge