name: .NET CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY_BASE: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

  build-and-push-images:
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write
    
    strategy:
      matrix:
        service: [ 'UserService.Api', 'TaskService.Api', 'ApiGateway' ]
        repo_name: [ 'user-service', 'task-service', 'api-gateway' ]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert repository name to lowercase
        if: github.event_name == 'push'
        id: ghcr_repo_owner
        shell: bash
        run: echo "repo_lowercase=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
        
      - name: Build, tag, and push image to ECR and GHCR
        env:
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY_BASE }}/${{ matrix.repo_name }}
          GHCR_REPOSITORY: ghcr.io/${{ steps.ghcr_repo_owner.outputs.repo_lowercase }}/${{ matrix.repo_name }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG -f src/${{ matrix.service }}/Dockerfile .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $GHCR_REPOSITORY:$IMAGE_TAG

          docker push $ECR_REPOSITORY:$IMAGE_TAG
          docker push $GHCR_REPOSITORY:$IMAGE_TAG